Test run

diff --git a/.github/workflows/release-genesis-creator.yml b/.github/workflows/release-genesis-creator.yml
--- a/.github/workflows/release-genesis-creator.yml
+++ b/.github/workflows/release-genesis-creator.yml
@@ -29,14 +29,14 @@ jobs:
         run: |
           # export VERSION=$(yq .package.version genesis-creator/Cargo.toml)
           export VERSION="0.8.0"
+          echo "version=${VERSION}" > "$GITHUB_OUTPUT
           # Make sure the tag matches the version in Cargo.toml manifest.
-          if [ ! "${{ github.ref_name }}" = "genesis-creator/${VERSION}" ]; then
-             echo "::error Expected tag ${{ github.ref_name }} does not match the version ${VERSION}."
-             #  exit 1
-             echo "version=${VERSION}" > "$GITHUB_OUTPUT"
-          else
-             # Store the version into a version variable for the following step.
-             echo "version=${VERSION}" > "$GITHUB_OUTPUT"
+          # if [ ! "${{ github.ref_name }}" = "genesis-creator/${VERSION}" ]; then
+          #    echo "::error Expected tag ${{ github.ref_name }} does not match the version ${VERSION}."
+          #    exit 1
+          # else
+          #    # Store the version into a version variable for the following step.
+          #    echo "version=${VERSION}" > "$GITHUB_OUTPUT"
 
   build-macos:
     name: Build and Sign Macos
