Final

diff --git a/.github/workflows/release-genesis-creator.yml b/.github/workflows/release-genesis-creator.yml
--- a/.github/workflows/release-genesis-creator.yml
+++ b/.github/workflows/release-genesis-creator.yml
@@ -1,14 +1,12 @@
 name: Publish genesis-creator binaries
 
 on:
-  # TODO: comment out temporarily
   # This release action always requires a tag to publish a release.
   # This job will run when a genesis-creator/$VERSION
   # tag is created.
-
   push:
-    branches:
-      - 'signing-of-genesis-creator-tool'
+    tags:
+      - genesis-creator/*.*.*
 
   workflow_dispatch:
 
@@ -82,13 +80,12 @@ jobs:
           # Verify the signature
           codesign --verify --verbose=4 "$BINARY_PATH"
 
-  # TODO: comment out temporarily
-  #     - name: Upload artifact
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: binary-macos-latest
-  #         path: |
-  #           target/release/genesis-creator
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: binary-macos-latest
+          path: |
+            target/release/genesis-creator
 
   build-windows:
     name: Build and Sign Windows
@@ -143,13 +140,12 @@ jobs:
             smctl sign --keypair-alias ${{ env.WINDOWS_SM_KEYPAIR_ALIAS }} --input target/release/genesis-creator.exe --config-file ${{ env.WINDOWS_PKCS11_CONFIG }} --verbose --exit-non-zero-on-fail --failfast
             smctl sign verify --input target/release/genesis-creator.exe
 
-  # TODO: comment out temporarily
-  #     - name: Upload artifact
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: binary-windows-latest
-  #         path: |
-  #           target\release\genesis-creator.exe
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: binary-windows-latest
+          path: |
+            target\release\genesis-creator.exe
 
   build-ubuntu:
     name: Build Ubuntu
@@ -168,47 +164,46 @@ jobs:
           rustup target add x86_64-unknown-linux-musl
           cargo build --locked --release --package genesis-creator --target x86_64-unknown-linux-musl
   
-  #     - name: Upload artifact
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: binary-ubuntu-latest
-  #         path: |
-  #           target/release/x86_64-unknown-linux-musl/genesis-creator
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: binary-ubuntu-latest
+          path: |
+            target/release/x86_64-unknown-linux-musl/genesis-creator
 
-  # TODO: comment out temporarily
   # Attach binaries to the release identified by the tag.
-  # release:
-  #   permissions:
-  #     contents: write
-  #   needs:  [build-windows, build-macos, build-ubuntu]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         submodules: recursive
-  # 
-  #     - uses: actions/download-artifact@v4
-  #     - run: |
-  #         mkdir uploads
-  #         mv binary-macos-latest/genesis-creator uploads/genesis-creator-darwin-amd64
-  #         mv binary-windows-latest/genesis-creator.exe uploads/genesis-creator-windows-amd64.exe
-  #         mv binary-ubuntu-latest/genesis-creator uploads/genesis-creator-linux-amd64
-  # 
-  #     - name: Extract version tag from Cargo.toml manifest.
-  #       id: meta
-  #       run: |
-  #         export VERSION=$(yq .package.version genesis-creator/Cargo.toml)
-  #         # Make sure the tag matches the version in Cargo.toml manifest.
-  #         if [ ! "${{ github.ref_name }}" = "genesis-creator/${VERSION}" ]; then
-  #            echo "::error Expected tag ${{ github.ref_name }} does not match the version ${VERSION}."
-  #            exit 1
-  #         else
-  #            # Store the version into a version variable for the following step.
-  #            echo "version=${VERSION}" > "$GITHUB_OUTPUT"
-  #         fi
-  # 
-  #     - name: Create release and attach binaries to release.
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       run: |
-  #         gh release create ${{ github.ref_name }} --title "Genesis Creator ${{ steps.meta.outputs.version }}" uploads/*
+  release:
+    permissions:
+      contents: write
+    needs:  [build-windows, build-macos, build-ubuntu]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: recursive
+  
+      - uses: actions/download-artifact@v4
+      - run: |
+          mkdir uploads
+          mv binary-macos-latest/genesis-creator uploads/genesis-creator-darwin-amd64
+          mv binary-windows-latest/genesis-creator.exe uploads/genesis-creator-windows-amd64.exe
+          mv binary-ubuntu-latest/genesis-creator uploads/genesis-creator-linux-amd64
+  
+      - name: Extract version tag from Cargo.toml manifest.
+        id: meta
+        run: |
+          export VERSION=$(yq .package.version genesis-creator/Cargo.toml)
+          # Make sure the tag matches the version in Cargo.toml manifest.
+          if [ ! "${{ github.ref_name }}" = "genesis-creator/${VERSION}" ]; then
+             echo "::error Expected tag ${{ github.ref_name }} does not match the version ${VERSION}."
+             exit 1
+          else
+             # Store the version into a version variable for the following step.
+             echo "version=${VERSION}" > "$GITHUB_OUTPUT"
+          fi
+  
+      - name: Create release and attach binaries to release.
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh release create ${{ github.ref_name }} --title "Genesis Creator ${{ steps.meta.outputs.version }}" uploads/*
